[build]


target = "aarch64-linux-android"

rustflags = [
    "-Z",
    "dwarf-version=4",
    "-C",
    "linker-plugin-lto",
    "-C",
    "force-unwind-tables=no",
]
target-dir = "../out/rust"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size"]
profile-rustflags = true

[profile.release]
rustflags = ["-Z", "location-detail=none", "-Z", "fmt-debug=none"]
