https://raw.githubusercontent.com/auroraOSP/random/main/keybox.xml
https://raw.githubusercontent.com/zuri1503/Toolbox-Database/main/keybox.xml
https://raw.githubusercontent.com/AresOS-AOSP/.github/main/profile/keybox.xml
https://raw.githubusercontent.com/Yurii0307/yurikey/main/key
https://raw.githubusercontent.com/yusufnoor786/vendor_certification/16.2/keybox.xml
https://raw.githubusercontent.com/hashcones/mkboxml/main/keybox.xml
http://evoker.qzz.io/key
https://raw.githubusercontent.com/meowdump/dump/main/key.txt
https://raw.githubusercontent.com/K3V1991/Keybox-Collection/main/keybox.xml
# ElDavoo KeyboxScavenger personal endpoint (updated periodically)
https://www.davidepalma.it/pib/keybox.xml
