
FINGERPRINT=google/tegu/tegu:17/CP2A.260705.006/15641320:user/release-keys
BRAND=google
DEVICE=tegu
MANUFACTURER=Google
MODEL=Pixel 9a
PRODUCT=tegu
ID=CP2A.260705.006
TAGS=release-keys
TYPE=user
SECURITY_PATCH=2026-07-01
DEVICE_INITIAL_SDK_INT=35
SDK_INT=37
RELEASE=17
INCREMENTAL=15641320
