FINGERPRINT=google/tegu_beta/tegu:CANARY/ZP11.260821.010/16290768:user/release-keys
BRAND=google
DEVICE=tegu
MANUFACTURER=Google
MODEL=Pixel 9a
PRODUCT=tegu_beta
ID=ZP11.260821.010
TAGS=release-keys
TYPE=user
SECURITY_PATCH=2026-09-05
DEVICE_INITIAL_SDK_INT=32
