android
com.android.vending
com.google.android.gsf
com.google.android.gms
com.google.android.ims
io.github.vvb2060.keyattestation
io.github.qwq233.keyattestation
io.github.vvb2060.mahoshojo
gr.nikolasspyr.integritycheck
com.eltavine.duckdetector
com.google.android.apps.walletnfcrel
com.google.android.apps.messaging
com.google.android.contactkeys
com.google.android.safetycore
icu.nullptr.nativetest
com.reveny.nativecheck
com.android.nativetest
stealth:ru.nspk.mirpay
ru.nspk.sbpay
ru.sberbankmobile
com.idamob.tinkoff.android
ru.vtb24.mobilebanking.android
ru.alfabank.mobile.android
ru.gazprombank.android.mobilebank.app
ru.raiffeisennews
ru.rosbank.android
ru.mkb.mobile
ru.rshb.dbo
ru.letobank.Prometheus
com.openbank
ru.sovcombank.halva
com.sovcombank.club
ru.yoo.money
com.yandex.bank
ru.ozon.fintech.finance
com.qiwi.wallet
com.axlebolt.standoff2
ru.foodfox.client
ru.sbcs.store
ru.instamart
ru.sbermarket
ru.kuper.app
ru.pyaterochka.app
ru.x5.p5
ru.yandex.eda
com.scottyab.rootbeer.sample
com.kimchangyoun.rootbeerFresh.sample
com.zhenxi.hunter
