
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.provideDelegate
import java.io.File
import java.util.Properties
import java.util.Random

// Set non-zero value here to fix the random seed for reproducible builds
// CI builds are always reproducible
val RAND_SEED = if (System.getenv("CI") != null) 42 else 0
lateinit var RANDOM: Random

private val props = Properties()

object Config {
    operator fun get(key: String): String? {
        val v = props[key] as? String ?: return null
        return v.ifBlank { null }
    }

    fun contains(key: String) = get(key) != null

    val version: String get() = get("version")!!
    val versionCode: Int get() = get("magisk.versionCode")!!.toInt()
    val stubVersion: String get() = get("magisk.stubVersion")!!
    val abiList: List<String> get() = get("abiList")!!.split(",")
    val toolAbiList: List<String> get() =
        (get("toolAbiList") ?: get("abiList")!!).split(",")
    val secureDir: String get() = get("secureDir") ?: "/data/adb"
    val mainBinName: String get() = get("buildId") ?: "ms"
    val dataDir: String get() = get("dataDir") ?: "ms"
    val dbName: String get() = get("dbName") ?: "ms.db"
    val internalDir: String get() = get("internalDir") ?: ".ms"
    val socketName: String get() = get("socketName") ?: "socket"
    val policyName: String get() = get("policyName") ?: "mpol"
    val bin32Name: String get() = get("bin32Name") ?: "ms32"
    val busyboxName: String get() = get("busyboxName") ?: "busybox"
    val ramdiskName: String get() = get("ramdiskName") ?: "ms"
    val stubName: String get() = get("stubName") ?: "stub.apk"
    val initLdName: String get() = get("initLdName") ?: "init-ld"
    val udongeDir: String get() = get("udongeDir") ?: "udonge"
    val udongeArchive: String get() = get("udongeArchive") ?: "udonge.bin"
    val backupConfig: String get() = get("backupConfig") ?: ".cfg"
    val redirPath: String get() = get("redirPath") ?: "/data/._init"
    val suCache: String get() = get("suCache") ?: ".su_cache"
    val tmpDir: String get() = get("tmpDir") ?: "/dev/tmp"
    val backupPrefix: String get() = get("backupPrefix") ?: "/data/ms_backup_"
    val stageScript: String get() = get("stageScript") ?: "udonge.sh"
}

fun Project.rootFile(path: String): File {
    val file = File(path)
    return if (file.isAbsolute) file
    else File(rootProject.file(".."), path)
}

class MagiskPlugin : Plugin<Project> {
    override fun apply(project: Project) = project.applyPlugin()

    private fun Project.applyPlugin() {
        initRandom(rootProject.file("dict.txt"))
        props.clear()

        // Get gradle properties relevant to Magisk
        props.putAll(properties.filter { (key, _) -> key.startsWith("magisk.") })

        // Load config.prop
        val configPath: String? by this
        val configFile = rootFile(configPath ?: "config.prop")
        if (configFile.exists()) {
            configFile.inputStream().use {
                val config = Properties()
                config.load(it)
                props.putAll(config)
            }
        }

        // Load flags.prop, generated by build.py
        val flagsProp = rootProject.layout.buildDirectory.file("flags.prop").get().asFile
        if (flagsProp.exists()) {
            flagsProp.inputStream().use {
                val flags = Properties()
                flags.load(it)
                props.putAll(flags)
            }
        }
    }
}
